### ISSUE TITLE
How to make changes in Persistable class

### ISSUE THREAD

**Issue by huzzoid** [iamironz/binaryprefs#42]
Hello! Thanks for this library.

I created singleton instance:
``` java  
BinaryPreferencesBuilder(context)
.keyEncryption(XorKeyEncryptionImpl(mySecretKey))  
.valueEncryption(AesValueEncryptionImpl(mySecretKey, MyInitialVector))  
.registerPersistable(MyClass.KEY, MyClass::class.java)  
.build()
```
  
And it is working as i expected. 
After some time i had to add some additional fields to my persistable, and i got UnsupportedClassVersionError
Cannot find Persistable type for .����G� key

I read migration section at the wiki but have no idea how to correctrly implement that and not sure that is related with my issue.

There is my Persistable class.
```
class MyClass: Persistable {
    companion object {
        val KEY = "MyClass"
    }

    override fun readExternal(input: DataInput) {
        login = input.readString()
        password = input.readString()
        expiration = input.readLong()
        saveTime = input.readLong()
        saveLocalTime = input.readLong()
    }

    override fun deepClone(): Persistable {
        val value = LogoPass()
        value.login = login
        value.password = password
        value.expiration = expiration
        value.saveTime = saveTime
        value.saveLocalTime = saveLocalTime
        return value
    }

    override fun writeExternal(out: DataOutput) {
        out.writeString(login)
        out.writeString(password)
        out.writeLong(expiration)
        out.writeLong(saveTime)
        out.writeLong(saveLocalTime)
    }

    var login: String = ""
    var password: String = ""
    var expiration: Long = 0
    var saveTime: Long = 0
    var saveLocalTime: Long = 0
}
```

saveLocalTime - new field

**Comment by iamironz** [comment]
Hi! What version of library do you use? 
Also one question: what key you use for fetching `Persistable` from preferences?
It looks like registered `Persistable` object key differs with key witch has been passed into `getPersistable` method.

**Comment by iamironz** [comment]
As you can see [this](https://github.com/iamironz/binaryprefs/blob/92e36794ce580b254a8ba61177e61d9a145f0780/library/src/main/java/com/ironz/binaryprefs/serialization/serializer/persistable/PersistableRegistry.java#L22-L27) code part trying to fetch registered `Persistable` class type for instantiation and deserialization of stored binary data

**Comment by iamironz** [comment]
I can recommend disable all encryption for checking how works simple fetching. Because most of problems is incorrect custom key/value encryption. Also I recommend to use bundled encryption algorithms and different keys for each of.

**Comment by huzzoid** [comment]
The original question based on 1.0.0-BETA-2.
Also i have tried 0.9.9.9, and caught another exception:
```
Caused by: com.ironz.binaryprefs.exception.FileOperationException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Can't read out of bounds array (71 bytes > 62 bytes). May be your read/write contract isn't mirror-implemented?
                                                                            at com.ironz.binaryprefs.task.Completable.completeBlockingUnsafe(Completable.java:44)
                                                                            at com.ironz.binaryprefs.BinaryPreferences.fetchCache(BinaryPreferences.java:60)
                                                                            at com.ironz.binaryprefs.BinaryPreferences.<init>(BinaryPreferences.java:40)
                                                                            at com.ironz.binaryprefs.BinaryPreferencesBuilder.build(BinaryPreferencesBuilder.java:205)
```
There is getting of my encription keys (this part has never been changed since first implementation):
```
private val INITIAL_VECTOR = "be or not to be that is the question".toByteArray()
private val SECRET_KEY = "be or not to be that is the question".toByteArray()

 val initialVector = Arrays.copyOf(INITIAL_VECTOR, 16)
  val secretKey = Arrays.copyOf(SECRET_KEY, 16)
  
BinaryPreferencesBuilder(context)
            .keyEncryption(XorKeyEncryptionImpl(secretKey))
            .valueEncryption(AesValueEncryptionImpl(secretKey, initialVector))
```
My experiment with disabled encription:
```
Caused by: com.ironz.binaryprefs.exception.FileOperationException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Can't read out of bounds array (expected size: LogoPass bytes > disk size: 71 bytes) for 62! keyMay be your read/write contract isn't mirror-implemented or old disk version is not backward compatible with new class version?
                                                                            at com.ironz.binaryprefs.task.FutureBarrier.completeBlockingUnsafe(FutureBarrier.java:44)
                                                                            at com.ironz.binaryprefs.BinaryPreferences.fetchCache(BinaryPreferences.java:52)
                                                                            at com.ironz.binaryprefs.BinaryPreferences.<init>(BinaryPreferences.java:40)
                                                                            at com.ironz.binaryprefs.BinaryPreferencesBuilder.createInstance(BinaryPreferencesBuilder.java:251)
                                                                            at com.ironz.binaryprefs.BinaryPreferencesBuilder.build(BinaryPreferencesBuilder.java:226)
```
As i can see there is migration required, but i'm not sure how to do it correctly. What is "old preferences" and "new preferences" at the docs?

**Comment by iamironz** [comment]
"old" - disk version means your old saving protocol for first version of `Persistable`.
"new" - means actual protocol which tries restore old saved data based on your first protocol version.
If you wanna use migration for your persistable you should follow mutual steps as in `java.io.Externalizable ` interface. Read manuals about it.
